### ISSUE TITLE
[PE-D][Tester B] Claim command success message

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-F13-2/tp#145]
![image.png](https://raw.githubusercontent.com/Weiennn/ped/main/files/89050cb9-1b56-40d4-873a-df45f110ff87.png)

Small UI issue, the second line "Remaining claim Alex Yeoh has: $4,060" has an extra space before it.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Weiennn/ped#5

**Comment by sheryew** [comment]
Solved
