### ISSUE TITLE
[PE-D][Tester D] Users are able to edit employees to create employees with the same name, disregarding case-sensitivity.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103-F13-2/tp#154]
![Screenshot (236).png](https://raw.githubusercontent.com/laurenlim2112/ped/main/files/3daf5d16-b3e6-4e95-ad05-50f7eeb5302e.png)
As stated in the title (and as seen from the screenshot), users can edit the names of employees to result in a situation with 1 employee named "Roy Balakrishnan" and the other named "roy balakrishnan".

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: laurenlim2112/ped#2

**Comment by remuslum** [comment]
We have decided to keep the current implementation as employees can have the same name and that alone is not enough of a criterion to determine that these 2 employees are the same person.
