### ISSUE TITLE
Filter by department improvements

### ISSUE THREAD

**Issue by nixonwidjaja** [AY2324S1-CS2103-F13-2/tp#61]
- make keyword case insensitive
- show error if invalid command e.g. list p/

**Comment by nixonwidjaja** [comment]
@marcellaantania I just read ArgumentMultimap.java and ArgumentTokenizer.java, turns out their implementation is to ignore any invalid params like list p/. Should we also ignore or treat it is a bug? What do you think?

But perhaps for all command we need to use `argMultimap.verifyNoDuplicatePrefixesFor()` like in `AddCommandParser.java` to prevent duplicate fields.

**Comment by marcellaantania** [comment]
> @marcellaantania I just read ArgumentMultimap.java and ArgumentTokenizer.java, turns out their implementation is to ignore any invalid params like list p/. Should we also ignore or treat it is a bug? What do you think?
> 
> But perhaps for all command we need to use `argMultimap.verifyNoDuplicatePrefixesFor()` like in `AddCommandParser.java` to prevent duplicate fields.

I feel like it's better to treat it as a bug, in case the user makes a typo when typing the prefixes. It can be misleading if the user writes list f/Engineering and gets the whole list of employees as a result, while expecting a department filtering.

Verifying duplicates is a good idea, maybe we should make a separate issue for it?
