### ISSUE TITLE
Add bug handling for invalid prefixes

### ISSUE THREAD

**Issue by marcellaantania** [AY2324S1-CS2103-F13-2/tp#71]
Currently, the implementation is to ignore invalid prefixes. However, a better implementation is to handle invalid parameters as a bug to notify users, in case they made a typo. This can be implemented in ArgumentMultimap and ArgumentTokenizer.

**Comment by marcellaantania** [comment]
> arameters.

**Comment by sheryew** [comment]
Test Case to try: view f/Engineering d/Engineering
